<?php

namespace App;
use Spatie\Activitylog\Traits\LogsActivity;
use Illuminate\Database\Eloquent\Model;

class Matriculas extends Model
{
    use LogsActivity;

    protected $fillable = [
        'empresa_id',
        'sede_id',
        'temporada_id',
        'grado_id',
        'paralelo_id',
        'alumno_id',
        'direccion_r',
        'barrio_r',
        'comuna_r',
        'municipio_r',
        'departamento_id',
        'estrato_id',
        'tipo_vivienda_id',
        'zona_id',
        'telefono_est',
        'celular_est',
        'email_est',
        'vive_con',
        'n_personas_hogar',
        'n_hermanos',
        'n_hermanos_col',
        'telefono_f',
        'icbf',
        'f_accion',
        'nee_id',
        'nee_texto',
        'nuevo_antiguo',
        'col_procede',
        'ciudad_procede',
        'dpto_id',
        'repitente',
        'jornada_id',
        'estatura',
        'peso',
        'hijo_heroe',
        'desvinculado',
        'desmovilizado',
        'nombres_acu',
        'apellidos_acu',
        'tipo_doc_id',
        'n_documento_acu',
        'expedida_acu',
        'direccion_acu',
        'telefono_acu',
        'celular_acu',
        'email_acu',
        'empresa_acu',
        'profesion_acu',
        'parentesco_acu',
        'nombre_eps',
        'beneficiario_sisben',
        'alergias',
        'medicamentos',
        'discapacidad',
        'etnia',
        'resguardo',
        'conflicto',
        'nombres_fac',
        'tipo_doc_fac_id',
        'n_documento_fac',
        'direccion_fac',
        'email_fac',
        'celular_fac',
        'token',
        'fin_token',
        'status',
        'user_create',
        'user_update'
    ];

    protected static $logName = 'AREAS';

    protected static $logAttributes = [
        'empresa_id',
        'sede_id',
        'temporada_id',
        'grado_id',
        'paralelo_id',
        'alumno_id',
        'direccion_r',
        'barrio_r',
        'comuna_r',
        'municipio_r',
        'departamento_id',
        'estrato_id',
        'tipo_vivienda_id',
        'zona_id',
        'telefono_est',
        'celular_est',
        'email_est',
        'vive_con',
        'n_personas_hogar',
        'n_hermanos',
        'n_hermanos_col',
        'telefono_f',
        'icbf',
        'f_accion',
        'nee_id',
        'nee_texto',
        'nuevo_antiguo',
        'col_procede',
        'ciudad_procede',
        'dpto_id',
        'repitente',
        'jornada_id',
        'estatura',
        'peso',
        'talla_cam',
        'talla_pan',
        'hijo_heroe',
        'desvinculado',
        'desmovilizado',
        'nombres_acu',
        'apellidos_acu',
        'tipo_doc_id',
        'n_documento_acu',
        'expedida_acu',
        'direccion_acu',
        'telefono_acu',
        'celular_acu',
        'email_acu',
        'empresa_acu',
        'profesion_acu',
        'parentesco_acu',
        'nombre_eps',
        'beneficiario_sisben',
        'alergias',
        'medicamentos',
        'discapacidad',
        'etnia',
        'resguardo',
        'conflicto',
        'nombres_fac',
        'tipo_doc_fac_id',
        'n_documento_fac',
        'direccion_fac',
        'email_fac',
        'celular_fac',
        'token',
        'fin_token',
        'status',
        'user_create',
        'user_update'
    ];
}



            